### ISSUE TITLE
Request to include 'pymol_launcher'

### ISSUE THREAD

**Issue by boneta** [cgohlke/pymol-open-source-wheels#1]
Hi Christoph,

Firstly, I would like to express my sincere gratitude for your work in providing an easy way to use the open-source PyMOL on Win. Your dedication and desire to continue contributing enormously benefit the entire scientific community and beyond.

While exploring the releases of this repo, I noticed that only the wheels for *pymol* were included, but not the ones for *pymol-launcher*. My colleagues and I have found the `PyMOL.exe` executable to be an incredibly useful component that facilitates the user experience. Although I have noticed that now a `Scripts/pymol.exe` can be used, it lacks several key functionalities such as a specific icon (in the launcher, pse/pdb/... files and context menu) or the ability to be pinned to the taskbar. These features are specially noticeable by the less tech-savvy users.

For this reasons, I kindly request if it would be possible to add the *pymol-launcher* wheels back to the release, as an optional installation step as it was before.

Thank you once again!

**Comment by cgohlke** [comment]
The pymol-launcher source code and wheels are included in the v2023.6.1 release. The launcher is using deprecated API calls and is not supported on pypy. Hope it works.
